# Generated by Django 6.1.1 on 2026-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
